---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Gather listed ACLs with provided configurations
      cisco.asa.asa_acls:
        config:
        state: gathered
      
      register: gathered

    - name: Show changes to interface from task above
      ansible.builtin.debug:
        var: gathered

