---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Parse the commands for provided configuration
      cisco.asa.asa_acls:
        running_config: "{{ lookup('file', '/home/automation/Ansible_automation_new/parsed.cfg') }}"
        state: parsed
      register: parsed_report

    - name: Show changes to interface from task above
      ansible.builtin.debug:
        var: parsed_report


