---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Set the ASCII banner on the Cisco Device
      cisco.asa.asa_config:
        lines:
          - no banner login      
          - banner login        d8888 888    888                      888    d8b                   888 
          - banner login       d88888 888    888                      888    Y8P                   888 
          - banner login      d88P888 888    888                      888                          888 
          - banner login     d88P 888 888888 888888  .d88b.  88888b.  888888 888  .d88b.  88888b.  888 
          - banner login    d88P  888 888    888    d8P  Y8b 888 "88b 888    888 d88""88b 888 "88b 888 
          - banner login   d88P   888 888    888    88888888 888  888 888    888 888  888 888  888 Y8P 
          - banner login  d8888888888 Y88b.  Y88b.  Y8b.     888  888 Y88b.  888 Y88..88P 888  888  "  
          - banner login d88P     888 "Y888  "Y888  "Y8888  888  888  "Y888 888  "Y88P"  888  888 888  

    - name: save running to startup when modified
      cisco.asa.asa_config:
        save_when: modified
                                                     
