---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Prints various Ansible facts
      debug:
        msg: "{{ ansible_facts.net_hostname }}"                                                                                                                                     
