---
- name: configure acls
  hosts: asa
  connection: network_cli
  gather_facts: yes
  become: yes
  become_method: enable
  tasks:
    - name: Gather legacy and resource facts
      cisco.asa.asa_config:
        lines:
        - description my cloud interface
        - nameif cloud13
        - security-level 50
        - ip address 192.168.13.1 255.255.255.0 standby 192.168.13.2
        - no shutdown
        parents: [interface GigabitEthernet0/5]
      register: interface
    - name: save running to startup when modified
      cisco.asa.asa_config:
        save_when: modified


    - name: Show changes to interface from task above
      ansible.builtin.debug:
        var: interface
 
